[build-system]
requires = ['setuptools']
build-backend = 'setuptools.build_meta'

[project]
name = 'aiosimpro'
version = '0.0.1'
dependencies = [
    'aiohttp==3.8.4',
]

[tool.setuptools.packages.find]
include = ['aiosimpro']
